###
##. Configuration
###

YACHT_PROJECTS_ROOT_DIR=$(shell cd ../../examples && pwd)

include ../../builtins.makefile
include ../../base.makefile
include ../../docker.makefile
include ../../docker-tools.makefile
