###
##. Configuration
###

YACHT_PROJECTS_ROOT_DIR=$(shell cd ../../examples && pwd)

include ../../base.makefile
include ../../help.makefile
include ../../docker.makefile
include ../../docker-tools.makefile
