###
##. Configuration
###

YACHT_PROJECTS_ROOT_DIR=$(shell cd ../../examples && pwd)

include ../../base.makefile

###
## About
###

include ../../help.makefile

###
## Docker
###

include ../../programs/docker.makefile

###
## Docker Tools
###

include ../../programs/curl.makefile
include ../../programs/jq.makefile
include ../../docker-tools/ctop.makefile
include ../../docker-tools/dive.makefile
include ../../docker-tools/dockly.makefile
include ../../docker-tools/dozzle.makefile
include ../../docker-tools/dry.makefile
include ../../docker-tools/hadolint.makefile
include ../../docker-tools/lazydocker.makefile
include ../../docker-tools/portainer.makefile
include ../../docker-tools/traefik.makefile
include ../../docker-tools/trivy.makefile
include ../../docker-tools/watchtower.makefile
include ../../docker-tools/yacht.makefile
