###
##. Configuration
###

YACHT_PROJECTS_ROOT_DIR=$(shell cd ../../examples && pwd)

include ../../base.makefile

###
## About
###

include ../../help.makefile

###
## Docker
###

include ../../programs/docker.makefile

###
## Docker Tools
###

include ../../programs/curl.makefile
include ../../programs/jq.makefile
include ../../docker-tools/*
