networks:

  traefik:
    external: true

services:

  php-sidecar:
    image: alpine
    command: sh -c 'echo "Ran some PHP related tasks successfully"'

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    environment:
      - "COMPOSER_HOME=/app/.composer"
    user: "${UID}:${GID}"
    working_dir: "/app"
    volumes:
      - ".:/app"
    networks:
      - traefik
